### PR TITLE
UX Enhancement for #69: Animations added to text elements (homepage),…

### PR DESCRIPTION
**Pull request by foss2cyber**
… Changed the default background colour for both light/dark modes

@prjctimg I've made some changes. Kindly review them. Attaching some screenshots below:
Screenshot_20231122_143426

Screenshot_20231122_143504

localhost_3000_

localhost_3000_(iPhone XR)

### CODE REVIEW

**Comment by prjctimg** [comment]
> … Changed the default background colour for both light/dark modes
> 
> @prjctimg I've made some changes. Kindly review them. Attaching some screenshots below: Screenshot_20231122_143426
> 
> Screenshot_20231122_143504
> 
> localhost_3000_
> 
> localhost_3000_(iPhone XR)



@foss2cyber Pardon the late response, we're having loadshedding issues here. 


I have reviewed your changes and would like to suggest some changes. For example, can you increase the padding on the card components and give the buttons a background with a rounded radius (maybe `rounded-md` et cetera).

And can you apply the change to the default background in light mode to only the card components? The background color for the card components should be the main background for the homepage. I think it would achieve a better contrast. 


Unfortunately the build is still strangely failing because of a yarn install error. I would have loved to see the animations in action! Have you tried deleting the yarn.lockfile ?

**Comment by prjctimg** [comment]
And can you please remove the date of publish from the card. It seems redundant in my humble opinion because it only makes sense if we were creating blog posts. 😂


For a more subtle UI, let's also omit the "Read more" text on the button with just an arrow pointing right.

**Comment by prjctimg** [comment]
And can you please remove the date of publish from the card. It seems redundant in my humble opinion because it only makes sense if we were creating blog posts. 😂


For a more subtle UI, let's also omit the "Read more" text on the button with just an arrow pointing right.

**Comment by prjctimg** [comment]
[Here's the build log](https://vercel.com/my-team-84794c1e/huetiful-docs/4w9fZ6FKbmruy24PYhHLPzkbeyhy)

**Comment by foss2cyber** [comment]
> And can you please remove the date of publish from the card. It seems redundant in my humble opinion because it only makes sense if we were creating blog posts. 😂
> 
> For a more subtle UI, let's also omit the "Read more" text on the button with just an arrow pointing right.

@prjctimg I'll get straight to implementing the changes you've suggested. :+1: Also, can you DM me on wa in case I don't respond instantly here? I'll be quick to respond.

**Comment by foss2cyber** [comment]
> @foss2cyber Pardon the late response, we're having loadshedding issues here.
> 
> I have reviewed your changes and would like to suggest some changes.
> 
>     * Can you please increase the padding on the card components. You could simply reset the padding the default.
> 
>     * Give the buttons on the card components a background with a rounded radius (maybe `rounded-md` et cetera).
> 
>     * And can you apply the change to the default background in light mode to only the card components? The color for the main background for the homepage should maintain a high contrast with a neutral background. You could try `gray-100`
> 
> 
> I would have loved to see the animations in action! 🚀
> 
> Unfortunately the build is still strangely failing because of a yarn install error. Have you tried deleting the yarn.lockfile ? Or is there a way we can just use the normal npm because yarn is starting to get on my nerves 😂

@prjctimg Yes, I did delete the yarn.lockfile, but nothing came out of that. Same old. We could use npm instead if we're okay with that option, too. Cheers!

**Comment by foss2cyber** [comment]
@prjctimg Have implemented all those changes you requested in the latest commit. Kindly review. Previous commit can be discarded. Also, the deployment succeeded this time.

**Review by prjctimg — APPROVED** [review]
Looks good 👍!
 Loving the neumorphic-like button design! 
Proceed 🚀

**Pull request merged**
